#!/bin/sh

BASE='/mnt/temp'
ROOT="${BASE}/roots/x86_64"
TOOLS='~/devel/master/debug/source/'
GDBX="/tmp/_${USER}_gdb_run"

echo """
#set solib-absolute-prefix ${ROOT}
#set debug-file-directory ${ROOT}/usr/lib/debug
#file ${BASE}/cores/service/binary
#core-file ${BASE}/cores/service/$1
attach $1
source ${TOOLS}/register.py
source ${TOOLS}/example/stats.py
""" > ${GDBX}

gdb -x ${GDBX}

