#!/usr/bin/env python2

from os         import listdir
from sys        import argv
from os.path    import abspath, expanduser, dirname
from inspect    import isfunction
from types      import GeneratorType

base = abspath(expanduser(dirname(__file__)))

prefix = argv[1] if len(argv) > 1 else ''

for name in sorted(listdir(base + '/test/')):
    if name.endswith('.py') and name.startswith(prefix):
        used = name[:-3]

        print '--', used

        mod = __import__('test.' + used)
        sub = getattr(mod, used)

        it = map(lambda x: getattr(sub, x), dir(sub))

        for some in filter(isfunction, it):
            if some.__name__.startswith('test_'):
                last = None

                try:
                    it = some()

                    if isinstance(it, GeneratorType):
                        for anchor in it:
                            last = anchor

                except Exception as E:
                    err = str(E)

                else:
                    err = None

                status  = 'OKAY' if err is None else 'FAIL'
                name    = some.__name__[len('test_'):]

                print  '    %2s %8s %s' % (status, last or '', name)

                if err is not None:
                    print '        %s' % err
